
proxies:

proxy-providers:
  
  可乐云:
    type: http
    url: "订阅链接地址"
    path: ./proxy_providers/可乐云.yaml
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800
  魔戒:
    type: http
    url: "订阅链接地址"
    path: ./proxy_providers/魔戒.yaml
    interval: 21600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800
#如果无法正常更新订阅，请打开proxy provider 里面的机场yaml配置文件，如果是乱码，需要自己在订阅链接结尾加上 &flag=clash  强制订阅服务器下发clash的配置文件
  备用:
    type: http
    url: "在底下选一个吧，如果有好的欢迎提交"
    path: ./proxy_providers/备用.yaml
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

#欢迎提交更多白嫖订阅
#https://v1.gs/RW308wN
#https://openit.daycat.space/clash
#https://nullnode.top/clash主站 下属 https://nullnode.top/clashnode
#可以白嫖的机场 https://acec.cloud/
# 魔戒 可乐云 为机场名，可以更换，要换必须全换，建议使用编辑器的查找功能避免遗漏
proxy-groups:
  - name: 机场
    type: select
    proxies:
      - 可乐云
      - 魔戒
      - 美国节点
      - 负载均衡
      - 备用

  - name: 可乐云
    type: select
    use:
      - 可乐云

  - name: 魔戒
    type: select
    use:
      - 魔戒

  - name: 美国节点
    type: select
    use:
      - 可乐云
      - 魔戒
      - 备用
    filter: '美国|USA|美國'
#meta的特性，如果你经常使用某个地区节点可以使用过滤器便于选择 美国节点 可以改为其他，要改全改 ，过滤器内容用 | 分割，支持通配符
#测试性增加了负载均衡节点
  - name: "负载均衡"
    type: load-balance
    use:
      - 可乐云
      - 魔戒
    url: 'http://www.gstatic.com/generate_204'
    interval: 1800
    filter: '美国|USA|美國.*1.0'
    strategy: consistent-hashing


  - name: 备用
    type: select
    use:
      - 备用

  - name: 墙内网址
    type: select
    proxies:
      - DIRECT
      - 机场

  - name: 其他
    type: select
    proxies:
      - 机场
      - 墙内网址

rule-providers:
  AD:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
    path: ./rule_providers/Ad.yaml
    interval: 21600
  Google:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
    path: ./rule_providers/Google.yaml
    interval: 21600
  GoogleFCM:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.yaml
    path: ./rule_providers/GoogleFCM.yaml
    interval: 21600
  WeChat:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.yaml
    path: ./rule_providers/WeChat.yaml
    interval: 21600
  BiliBili:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml
    path: ./rule_providers/BiliBili.yaml
    interval: 21600
  Tencent:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.yaml
    path: ./rule_providers/Tencent.yaml
    interval: 21600
  AppProxy:
    type: file
    behavior: classical
    path: ./rule_providers/AppProxy.yaml
  AppDirect:
    type: file
    behavior: classical
    path: ./rule_providers/AppDirect.yaml
  userDirect:
    type: file
    behavior: classical
    path: ./rule_providers/userDirect.yaml
    #用户自定义直连，文件在data/clash/rule-provider/userdirect，需要的自己写入，格式参照备用里面的clash官方文档
  Local:
    type: file
    behavior: classical
    path: ./rule_providers/Locale.yaml
rules:
  #- PROCESS-NAME,clash,REJECT # 解决回环小妙招 打开会导致无法手动更新订阅，只能等待自动更新
  - RULE-SET,AppProxy,机场
  - RULE-SET,AppDirect,墙内网址
  - RULE-SET,userDirect,墙内网址
  - RULE-SET,AD,REJECT # 去广告规则，要用，去掉最前面的井号即可
  - RULE-SET,BiliBili,墙内网址,no-resolve
  - RULE-SET,Tencent,墙内网址
  - RULE-SET,WeChat,墙内网址
  - RULE-SET,Local,DIRECT
  - RULE-SET,Google,机场
  - GEOSITE,CN,墙内网址
  - GEOIP,CN,墙内网址
  - MATCH,机场
